/* Pennant — Copyright (c) 2026 Luka Gale. MIT licence. */
/* Executes every inline page script in a stubbed DOM. Catches ReferenceError,
   temporal dead zone and any other load-time throw that `node --check` cannot
   see, because --check only parses and never runs.

   Changes from the previous version, and why:

   1. The old regex /<script>\n([\s\S]*)\n<\/script>/ is greedy. With two or
      more inline <script> blocks it matched from the FIRST opening tag to the
      LAST closing tag and fed the intervening markup to the parser, producing
      a syntax error unrelated to the code. It also ignored <script> tags that
      carried attributes, and `re.exec(...)[1]` threw `TypeError: null[1]` when
      nothing matched at all — a confusing crash instead of a message.
      Now: every inline block is found, external <script src=...> is skipped,
      and zero blocks is a clear failure.

   2. requestAnimationFrame was stubbed as `f => f()`, i.e. synchronous. Any
      ordinary render loop (`function frame(){ ...; requestAnimationFrame(frame) }`)
      recursed until the stack blew, so the harness rejected correct code.
      Now: the callback runs at most twice, so the body is still exercised. */

const fs = require('fs');
const path = require('path');

const files = process.argv.slice(2);
if (files.length === 0) {
  console.log('usage: node tools/smoke.js <file.html> [more.html ...]');
  process.exit(2);
}

// Inline scripts only: a src attribute means the body is empty.
//
// This is a forward scan rather than a regex, and it has to be. Two real cases
// in this codebase defeat the obvious approaches:
//
//   1. A <script> mentioned inside an HTML comment. Matching non-greedily from
//      that fake opening tag runs the body to the *real* </script>, so the real
//      block never matches at all and the harness silently tests nothing.
//   2. The page emits HTML comments as JavaScript strings — `'<!-- Generated by'`.
//      Blanking every <!-- ... --> before matching therefore deletes live code
//      between a string and some later real comment, and reports a syntax error
//      in code that is fine.
//
// Scanning left to right with a mode fixes both: outside a script, "<!--" starts
// a comment to skip; inside a script, "<!--" is just characters. Whichever of
// the two markers comes first wins, which is roughly what an HTML parser does.
//
// A literal "</script" inside a JS string would still end the block early — but
// that ends it in a browser too, so matching that behaviour is correct.
function inlineScripts(html) {
  const out = [];
  let i = 0;
  while (i < html.length) {
    const c = html.indexOf('<!--', i);
    const m = /<script\b([^>]*)>/i.exec(html.slice(i));
    const sPos = m ? i + m.index : -1;

    if (sPos === -1 && c === -1) break;
    if (c !== -1 && (sPos === -1 || c < sPos)) {  // a comment comes first: skip it
      const end = html.indexOf('-->', c + 4);
      i = end === -1 ? html.length : end + 3;
      continue;
    }

    // A script tag comes first.
    const attrs = m[1] || '';
    const bodyStart = sPos + m[0].length;
    const close = html.toLowerCase().indexOf('</script', bodyStart);
    const bodyEnd = close === -1 ? html.length : close;
    const body = html.slice(bodyStart, bodyEnd);

    const external = /\bsrc\s*=/i.test(attrs);
    const badType = /\btype\s*=\s*["']?(?!(text\/javascript|module|application\/javascript))/i.test(attrs);
    if (!external && !badType && body.trim() !== '') out.push(body);

    i = close === -1 ? html.length : html.indexOf('>', close) + 1 || html.length;
  }
  return out;
}

function installStubs() {
  const el = () => ({
    classList: { toggle() {}, add() {}, remove() {}, contains() { return false; } },
    style: {}, dataset: {}, value: '', checked: false, disabled: false, hidden: false,
    addEventListener() {}, removeEventListener() {}, appendChild() {}, remove() {},
    click() {}, submit() {}, insertAdjacentHTML() {}, setAttribute() {},
    getAttribute: () => null, removeAttribute() {}, focus() {}, blur() {},
    querySelector: () => null, querySelectorAll: () => [],
    getBoundingClientRect: () => ({ width: 720, height: 260, top: 0, left: 0 }),
    clientWidth: 720, clientHeight: 260, offsetWidth: 720, offsetHeight: 260,
    set innerHTML(v) {}, get innerHTML() { return ''; },
    set textContent(v) {}, get textContent() { return ''; },
    onclick: null, onsubmit: null,
  });

  global.document = {
    getElementById: () => el(),
    querySelector: () => null,
    querySelectorAll: () => [],
    createElement: () => el(),          // deliberately no getContext: canvas code
    addEventListener() {},              // must degrade, not throw
    removeEventListener() {},
    body: el(), documentElement: el(), hidden: false, readyState: 'complete',
  };
  global.window = {
    addEventListener() {}, removeEventListener() {},
    localStorage: { getItem: () => null, setItem() {}, removeItem() {} },
    location: { hash: '', href: 'http://localhost/', pathname: '/' },
    matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }),
    devicePixelRatio: 1, innerWidth: 1280, innerHeight: 800,
    setTimeout: (f) => 0, clearTimeout() {},
  };
  global.localStorage = window.localStorage;
  global.location = window.location;
  global.matchMedia = window.matchMedia;
  global.devicePixelRatio = 1;
  global.getComputedStyle = () => ({ getPropertyValue: () => '' });
  global.navigator = { sendBeacon: () => true, clipboard: { writeText: async () => {} } };
  global.fetch = async () => ({ ok: false, status: 0, json: async () => ({}), text: async () => 'stub: no server' });
  global.Blob = class {};
  global.URL = { createObjectURL: () => '', revokeObjectURL() {} };
  global.FileReader = class { readAsText() {} readAsDataURL() {} };
  global.vis = undefined;
  global.Chart = undefined;
  global.performance = { now: () => 0 };

  let frames = 0;
  global.requestAnimationFrame = (f) => { if (frames++ < 2) f(0); return frames; };
  global.cancelAnimationFrame = () => {};
}

process.on('unhandledRejection', () => {});   // a failed boot() fetch is expected

installStubs();

let failed = 0;
for (const file of files) {
  let html;
  try {
    html = fs.readFileSync(file, 'utf8');
  } catch (e) {
    console.log('READ FAIL ' + file + '\n  ' + e.message);
    failed++;
    continue;
  }
  const blocks = inlineScripts(html);
  if (blocks.length === 0) {
    console.log('LOAD FAIL ' + file + '\n  no inline <script> block found');
    failed++;
    continue;
  }
  let ok = true;
  blocks.forEach((src, i) => {
    if (!ok) return;
    try {
      new Function(src)();
    } catch (e) {
      const where = blocks.length > 1 ? ' (block ' + (i + 1) + ' of ' + blocks.length + ')' : '';
      console.log('LOAD FAIL ' + file + where + '\n  ' + e.constructor.name + ': ' + e.message);
      ok = false;
      failed++;
    }
  });
  if (ok) {
    console.log('LOAD OK   ' + path.basename(file) + '  (' + blocks.length + ' script block' + (blocks.length > 1 ? 's' : '') + ')');
  }
}
process.exit(failed === 0 ? 0 : 1);
